=== AnastasiaAvramova/AirLine/XMLDocuments/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NewXMLSchema" xmlns:tns="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">
	<element name="planeList" type="tns:PlaneList">
	</element>
	<complexType name="PlaneList">
		<sequence>
			<element name="airPlane" type="tns:AirbagPlane" minOccurs="1" maxOccurs="unbounded" />
			<element name="hydroPlane" type="tns:HydroPlane" minOccurs="1" maxOccurs="unbounded" />
			<element name="bobberedPlane" type="tns:BobberedPlane" minOccurs="1" maxOccurs="unbounded" />
			<element name="skiedPlane" type="tns:SkiedChassisPlane" minOccurs="1" maxOccurs="unbounded" />
			<element name="wheeledPlane" type="tns:WheeledChassisPlane" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="AbstractPlane" abstract="true">
		<sequence>
			<element name="cruisingSpeed" type="positiveInteger" />
			<element name="flyingDistance" type="tns:FlyingDistanceType" />
			<element name="cargoCapacity" type="positiveInteger" />
			<element name="seatsNumber" type="positiveInteger" />
			<element name="fuelExpenditure" type="positiveInteger" />
			<element name="bortNumber" type="tns:BortNumber" />
		</sequence>
		<attribute name="id" type="ID" use="required" />
		<attribute name="height" type="positiveInteger" use="required" />
		<attribute name="weight" type="positiveInteger" use="required" />
		<attribute name="lenght" type="positiveInteger" use="required" />
		<attribute name="wingspan" type="positiveInteger" use="required" />
	</complexType>
	<complexType name="AirbagPlane">
		<complexContent>
			<extension base="tns:AbstractPlane">
				<sequence>
					<element name="airbagMotorPower" type="positiveInteger" minOccurs="1" maxOccurs="1"/>
					<element name="airbagMotorName" type="string" minOccurs="1" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="HydroPlane">
		<complexContent>
			<extension base="tns:AbstractPlane">
				<sequence>
					<element name="seaworthiness" type="tns:SeeWorthiness" minOccurs="1" maxOccurs="1"/>
					<element name="maxWaveHeight" type="positiveInteger" minOccurs="1" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="BobberedPlane">
		<complexContent>
			<extension base="tns:HydroPlane">
				<sequence>
					<element name="bobbersNumber" type="positiveInteger" minOccurs="1" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="SkiedChassisPlane">
		<complexContent>
			<extension base="tns:AbstractPlane">
				<sequence>
					<element name="skiLength" type="positiveInteger" minOccurs="1" maxOccurs="1"/>
					<element name="skiWidth" type="positiveInteger" minOccurs="1" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="WheeledChassisPlane">
		<complexContent>
			<extension base="tns:AbstractPlane">
				<sequence>
					<element name="root" type="positiveInteger" minOccurs="1" maxOccurs="1"/>
					<element name="base" type="positiveInteger" minOccurs="1" maxOccurs="1"/>
					<element name="mainWheeelDiameter" type="tns:WheelDiameter" minOccurs="1" maxOccurs="1"/>
					<element name="backWheeelDiameter" type="tns:WheelDiameter" minOccurs="1" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<simpleType name="SeeWorthiness">
		<restriction base="positiveInteger">
			<enumeration value="1" />
			<enumeration value="2" />
			<enumeration value="3" />
		</restriction>
	</simpleType>
	<simpleType name="WheelDiameter">
		<restriction base="positiveInteger">
			<minInclusive value="1" />
			<maxInclusive value="5" />
		</restriction>
	</simpleType>
	<simpleType name="BortNumber">
		<restriction base="string">
			<pattern value="[1-9](0-9)*'-'[A-Z]" />
		</restriction>
	</simpleType>
	<simpleType name="BobersNumber">
		<restriction base="positiveInteger">
			<enumeration value="1" />
			<enumeration value="2" />
			<enumeration value="3" />
		</restriction>
	</simpleType>
	<simpleType name="FlyingDistanceType">
		<restriction base="positiveInteger">
			<enumeration value="2000" />
			<enumeration value="3000" />
			<enumeration value="4000" />
			<enumeration value="10000" />
		</restriction>
	</simpleType>
</schema>

=== AnastasiaAvramova/AirLine/XMLDocuments/Planes.xml
<?xml version="1.0" encoding="UTF-8"?>
<planeList xmlns:tns="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/NewXMLSchema NewXMLSchema.xsd ">
  <airPlane height="3" id="Ap1" lenght="5" weight="2000" wingspan="3">
    <cruisingSpeed>500</cruisingSpeed>
    <flyingDistance>2000</flyingDistance>
    <cargoCapacity>1000</cargoCapacity>
    <seatsNumber>20</seatsNumber>
    <fuelExpenditure>150</fuelExpenditure>
    <bortNumber>123-A</bortNumber>
    <airbagMotorPower>150</airbagMotorPower>
    <airbagMotorName>AirMotor1</airbagMotorName>
  </airPlane>
    <airPlane height="3" id="Ap2" lenght="5" weight="2000" wingspan="3">
    <cruisingSpeed>500</cruisingSpeed>
    <flyingDistance>2000</flyingDistance>
    <cargoCapacity>1000</cargoCapacity>
    <seatsNumber>20</seatsNumber>
    <fuelExpenditure>70</fuelExpenditure>
    <bortNumber>124-A</bortNumber>
    <airbagMotorPower>150</airbagMotorPower>
    <airbagMotorName>AirMotor1</airbagMotorName>
  </airPlane>
  <hydroPlane height="3" id="Hp1" lenght="4" weight="1000" wingspan="2">
    <cruisingSpeed>300</cruisingSpeed>
    <flyingDistance>2000</flyingDistance>
    <cargoCapacity>500</cargoCapacity>
    <seatsNumber>10</seatsNumber>
    <fuelExpenditure>50</fuelExpenditure>
    <bortNumber>123-H</bortNumber>
    <seaworthiness>2</seaworthiness>
    <maxWaveHeight>5</maxWaveHeight>
  </hydroPlane>
  <hydroPlane height="3" id="Hp2" lenght="4" weight="1000" wingspan="2">
    <cruisingSpeed>300</cruisingSpeed>
    <flyingDistance>2000</flyingDistance>
    <cargoCapacity>500</cargoCapacity>
    <seatsNumber>10</seatsNumber>
    <fuelExpenditure>50</fuelExpenditure>
    <bortNumber>124-H</bortNumber>
    <seaworthiness>2</seaworthiness>
    <maxWaveHeight>5</maxWaveHeight>
  </hydroPlane>
  <bobberedPlane height="2" id="Bp1" lenght="4" weight="1000" wingspan="3">
    <cruisingSpeed>200</cruisingSpeed>
    <flyingDistance>2000</flyingDistance>
    <cargoCapacity>300</cargoCapacity>
    <seatsNumber>15</seatsNumber>
    <fuelExpenditure>50</fuelExpenditure>
    <bortNumber>123-B</bortNumber>
    <seaworthiness>2</seaworthiness>
    <maxWaveHeight>2</maxWaveHeight>
    <bobbersNumber>2</bobbersNumber>
  </bobberedPlane>
    <bobberedPlane height="2" id="Bp2" lenght="4" weight="1000" wingspan="3">
    <cruisingSpeed>200</cruisingSpeed>
    <flyingDistance>2000</flyingDistance>
    <cargoCapacity>300</cargoCapacity>
    <seatsNumber>15</seatsNumber>
    <fuelExpenditure>50</fuelExpenditure>
    <bortNumber>124-B</bortNumber>
    <seaworthiness>2</seaworthiness>
    <maxWaveHeight>2</maxWaveHeight>
    <bobbersNumber>3</bobbersNumber>
  </bobberedPlane>
  <skiedPlane height="3" id="Sp1" lenght="6" weight="2000" wingspan="3">
    <cruisingSpeed>700</cruisingSpeed>
    <flyingDistance>3000</flyingDistance>
    <cargoCapacity>1000</cargoCapacity>
    <seatsNumber>50</seatsNumber>
    <fuelExpenditure>150</fuelExpenditure>
    <bortNumber>123-S</bortNumber>
    <skiLength>5</skiLength>
    <skiWidth>1</skiWidth>
  </skiedPlane>
    <skiedPlane height="3" id="Sp2" lenght="6" weight="2000" wingspan="3">
    <cruisingSpeed>700</cruisingSpeed>
    <flyingDistance>3000</flyingDistance>
    <cargoCapacity>1000</cargoCapacity>
    <seatsNumber>50</seatsNumber>
    <fuelExpenditure>150</fuelExpenditure>
    <bortNumber>124-S</bortNumber>
    <skiLength>5</skiLength>
    <skiWidth>1</skiWidth>
  </skiedPlane>
  <wheeledPlane height="3" id="Wp1" lenght="6" weight="2000" wingspan="3">
    <cruisingSpeed>700</cruisingSpeed>
    <flyingDistance>3000</flyingDistance>
    <cargoCapacity>1000</cargoCapacity>
    <seatsNumber>50</seatsNumber>
    <fuelExpenditure>150</fuelExpenditure>
    <bortNumber>123-W</bortNumber>
    <root>1</root>
    <base>3</base>
    <mainWheeelDiameter>2</mainWheeelDiameter>
    <backWheeelDiameter>1</backWheeelDiameter>
  </wheeledPlane>
    <wheeledPlane height="3" id="Wp2" lenght="6" weight="2000" wingspan="3">
    <cruisingSpeed>700</cruisingSpeed>
    <flyingDistance>3000</flyingDistance>
    <cargoCapacity>1000</cargoCapacity>
    <seatsNumber>50</seatsNumber>
    <fuelExpenditure>150</fuelExpenditure>
    <bortNumber>124-W</bortNumber>
    <root>1</root>
    <base>3</base>
    <mainWheeelDiameter>2</mainWheeelDiameter>
    <backWheeelDiameter>1</backWheeelDiameter>
  </wheeledPlane>
</planeList>
